// macOS status-bar presence for the detached daemon.
//
// The daemon outlives the GUI by design, so while the app runs, the menu bar
// shows whether its daemon is up: the tray exists if and only if the socket is
// connected. This module is pure and dependency-free (the Electron Tray/Menu
// objects are injected) so the lifecycle is unit-tested without a display.

// Monochrome tile-and-node glyph, generated by scripts/make-tray-icon.mjs.
// Loaded as a template image so the system inverts it on dark menu bars.
export const TRAY_ICON_DATA_URL =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAnUlEQVR4nO2WzQ3AIAiF30gdoSN0BDdzFEdwBEdpL5gQDq1iK43hS7gY0Qf4A+A4zjMHgATg7LREvkNExcbS4kjkfKFMUbVYFr6qTPC0B4V/EOXohkeuhWdCLUClnkhfC9jJpgvYABQ2p9DYNAFFnPIqYoqA/ebOy3KsKQDWJcAfDmHF7Bq28ooAs6fY/DMy/45h3ZDwTJi1ZI6zPhda+c3p+O43rQAAAABJRU5ErkJggg==";

export interface DaemonTrayHandle {
  destroy(): void;
  setToolTip(tip: string): void;
  setContextMenu(menu: unknown): void;
  popUpContextMenu(): void;
  onClick(fn: () => void): void;
}

/**
 * Reconcile the tray with daemon liveness. Returns the handle to keep.
 * Disconnect destroys (no dead icon lingers); connect creates once and
 * refreshes tip and menu after that.
 */
export function syncDaemonTray(
  current: DaemonTrayHandle | null,
  opts: {
    connected: boolean;
    tooltip: string;
    create(): DaemonTrayHandle;
    menu(): unknown;
  }
): DaemonTrayHandle | null {
  if (!opts.connected) {
    current?.destroy();
    return null;
  }
  const tray = current ?? opts.create();
  if (current === null) {
    tray.onClick(() => tray.popUpContextMenu());
  }
  tray.setToolTip(opts.tooltip);
  tray.setContextMenu(opts.menu());
  return tray;
}
